### ISSUE TITLE
Running Sample produces error 

### ISSUE THREAD

**Issue by dmason511** [SimonCropp/NServiceBus.Mailer#1]
Does this project require Raven?
I do not see a ref for it. 

I have Raven Installed on same machine

Running sample I get this error on 
var bus = configure
            .CreateBus()
            .Start(() => Configure.Instance.ForInstallationOn<Windows>().Install());

An exception of type 'System.InvalidOperationException' occurred in Raven.Client.Lightweight but was not handled in user code

Additional information: Url: "/docs/Raven/Authorization/WindowsSettings"

Any help would be greatly appreciated.

Any thoughts about updating package in the near future?

**Comment by SimonCropp** [comment]
updated to NSB version 5

fixed the sample
