### ISSUE TITLE
NServicebus 8

### ISSUE THREAD

**Issue by ghost** [SimonCropp/NServiceBus.Mailer#12]
We just upgraded from NServicebus 7.0 to 8.0. But I get an error in

UseSmtpBuilder() =>
            {
                ....
            });

Set method is not implemented anymore!? What shall I use now?

**Comment by JimGorman17** [comment]
Yes - Can confirm. This is a breaking issue.

**Comment by ramonsmits** [comment]
I created the following PR's. Lets see if @HEskandari has availability to release new versions:

- https://github.com/HEskandari/NServiceBus.Mailer/pull/13
- https://github.com/HEskandari/NServiceBus.Mailer/pull/14

**Comment by HEskandari** [comment]
Apologies for delayed action on this issue. I didn't notice this until just now due to a messed up notification. This will be released soon.

**Comment by JimGorman17** [comment]
> Apologies for delayed action on this issue. I didn't notice this until just now due to a messed up notification. This will be released soon.

@HEskandari Any ETA?

**Comment by HEskandari** [comment]
@JimGorman17 The latest v7.0.0 that targets .NET 8 and NServiceBus >= 9.0.2 has been released. Would that work for you?
