### ISSUE TITLE
Dotnet Core Compatibility

### ISSUE THREAD

**Issue by ChrisMurphy** [SimonCropp/NServiceBus.Mailer#5]
I am trying out the NserviceBus 7.0.0-rc0001 in a pure DotNet Core project along with NServiceBus.Mailer.  However I am getting warnings that the package is being restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'.

This is completely understandable but do you plan / is it possible to have a version of NServiceBus.Mailer that will be compatible in this way going forward?

I am using 4.0.0-beta003 by the way.

**Comment by SimonCropp** [comment]
@ChrisMurphy care to submit a PR?

**Comment by HEskandari** [comment]
@ChrisMurphy the latest releases track netstandard 2.0. As the last remnants, I have updated the sample project to also run on netcore. Closing this as resolved.
