### ISSUE TITLE
Configure queue name.

### ISSUE THREAD

**Issue by Blotulf** [SimonCropp/NServiceBus.Mailer#6]
Is it possible to configure the queue name by code?

**Comment by HEskandari** [comment]
@Blotulf Care to explain why you'd need to config the queue name?

**Comment by Blotulf** [comment]
@HEskandari I no longer work at the Company where we used NServiceBus and I cannot remember exactly why. I think it had something to do with using one azure storage queue account for different environments and the mail queue name was the same on the different environments causing one environment sending emails created on another environment causing some problems. I think we solved it by using separate accounts for each environment instead. I'm closing this issue now.
